# Generated by Django 3.0.4 on 2020-04-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_atualizacao', models.DateField()),
                ('data_notificacao', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
                ('cep', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('data_primeiros_sintomas', models.DateField()),
                ('paciente_hospitalizado', models.CharField(max_length=10)),
                ('data_internacao', models.DateField()),
                ('data_alta', models.DateField()),
                ('data_isolamento', models.DateField()),
            ],
        ),
    ]
