# Generated by Django 3.0.4 on 2020-04-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data_alta',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data_internacao',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data_isolamento',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data_notificacao',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data_primeiros_sintomas',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='paciente_hospitalizado',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sexo',
        ),
        migrations.AddField(
            model_name='notification',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='notification',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
