# Generated by Django 3.0.4 on 2020-04-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_listener'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='classificacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='coleta_amostra',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='coleta_exames',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_alta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_atualizacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_internacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_notificacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='endereco',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='estado_residencia',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='evolucao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='internado',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='municipio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='paciente_hospitalizado',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='pais_residencia',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='resultado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='situacao_notificacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='ventilacao_mecanica',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
