# Generated by Django 3.0.4 on 2020-04-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200403_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Bairro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
