# Generated by Django 3.0.4 on 2020-04-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200403_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Bairro',
            new_name='bairro',
        ),
        migrations.AlterField(
            model_name='notification',
            name='sexo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
