# Generated by Django 3.0.4 on 2020-04-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200403_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listener',
        ),
    ]
