# Generated by Django 3.0.4 on 2020-04-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_predictions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Predictions',
            new_name='Prediction',
        ),
    ]
