# Generated by Django 3.0.5 on 2020-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20200405_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data_chegada_brasil',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_ida_outro_local_transmissao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_isolamento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_primeiros_sintomas',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_volta_outro_local_transmissao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='estado_notificacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='foi_outro_local_transmissao',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='municipio_notificacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='outro_local_transmissao',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
