# Generated by Django 3.0.5 on 2020-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_remove_prediction_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interpolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('prediction', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='prediction',
            new_name='prediction1',
        ),
        migrations.AddField(
            model_name='prediction',
            name='prediction2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='prediction3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='bairro',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='cep',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='classificacao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='coleta_amostra',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='coleta_exames',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='endereco',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='estado_notificacao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='estado_residencia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='evolucao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='foi_outro_local_transmissao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='internado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='municipio',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='municipio_notificacao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='outro_local_transmissao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='paciente_hospitalizado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pais_residencia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='resultado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sexo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='situacao_notificacao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ventilacao_mecanica',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
