# Generated by Django 3.0.5 on 2020-04-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_accesskey_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='prediction',
            new_name='prediction1',
        ),
        migrations.AddField(
            model_name='prediction',
            name='prediction2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='prediction3',
            field=models.FloatField(null=True),
        ),
    ]
