# Generated by Django 3.0.5 on 2020-04-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20200415_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interpolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('prediction', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
