# Generated by Django 3.0.5 on 2020-04-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_casoscidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CasosCidades',
            new_name='CasosCidade',
        ),
    ]
