# Generated by Django 3.0.5 on 2020-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_auto_20200427_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficosPredicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ImageField(upload_to='grafico_modelo')),
                ('predicao', models.ImageField(upload_to='grafico_predicao')),
                ('projecao', models.ImageField(upload_to='grafico_projecao')),
            ],
        ),
    ]
