# Generated by Django 3.0.5 on 2020-04-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_graficospredicao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraficosPredicao',
        ),
    ]
