# Generated by Django 3.0.5 on 2020-05-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_auto_20200503_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casoscidade',
            old_name='confirmados',
            new_name='quantidade_casos',
        ),
        migrations.RenameField(
            model_name='casosestado',
            old_name='confirmados',
            new_name='quantidade_casos',
        ),
    ]
