# Generated by Django 3.0.5 on 2020-05-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_auto_20200503_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casoscidade',
            old_name='estado_residencia',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='casoscidade',
            old_name='quantidade_casos',
            new_name='confirmados',
        ),
        migrations.RenameField(
            model_name='casoscidade',
            old_name='data_notificacao',
            new_name='data_atualizacao',
        ),
        migrations.RenameField(
            model_name='casoscidade',
            old_name='municipio',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='casosestado',
            old_name='quantidade_casos',
            new_name='confirmados',
        ),
        migrations.RenameField(
            model_name='casosestado',
            old_name='data_notificacao',
            new_name='data_atualizacao',
        ),
        migrations.RenameField(
            model_name='casosestado',
            old_name='estado_residencia',
            new_name='estado',
        ),
    ]
