# Generated by Django 3.0.5 on 2020-05-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_casosestadohistorico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casosestadohistorico',
            old_name='data_atualizacao',
            new_name='data_notificacao',
        ),
        migrations.RenameField(
            model_name='casosestadohistorico',
            old_name='estado',
            new_name='estado_residencia',
        ),
        migrations.RenameField(
            model_name='casosestadohistorico',
            old_name='confirmados',
            new_name='quantidade_casos',
        ),
    ]
