# Generated by Django 3.0.5 on 2020-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_auto_20200506_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_notificacao', models.DateField(null=True)),
                ('quantidade_casos', models.IntegerField(null=True)),
                ('estado_residencia', models.CharField(max_length=150, null=True)),
                ('lo80', models.IntegerField(null=True)),
                ('hi80', models.IntegerField(null=True)),
                ('lo95', models.IntegerField(null=True)),
                ('hi95', models.IntegerField(null=True)),
            ],
        ),
    ]
