# Generated by Django 3.0.5 on 2020-05-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_projecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasosPernambuco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateField(null=True)),
                ('obitos', models.IntegerField(null=True)),
                ('recuperados', models.IntegerField(null=True)),
                ('isolamento', models.IntegerField(null=True)),
                ('internados', models.IntegerField(null=True)),
            ],
        ),
    ]
