# Generated by Django 3.0.5 on 2020-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_casospernambuco'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
