# Generated by Django 3.0.5 on 2020-05-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_userprofileinfo_instituicao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interpolation',
            new_name='InterpolationBR',
        ),
        migrations.RenameModel(
            old_name='Prediction',
            new_name='PredictionBR',
        ),
    ]
