# Generated by Django 3.0.5 on 2020-05-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_auto_20200515_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpolationPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('prediction', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('prediction1', models.FloatField(null=True)),
                ('prediction2', models.FloatField(null=True)),
                ('prediction3', models.FloatField(null=True)),
            ],
        ),
    ]
